export const photos = [
  {
    id: 1,
    url: "https://picsum.photos/298",
    name: "Leanne",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Sincere@april.biz",
  },
  {
    id: 2,
    url: "https://picsum.photos/299",
    name: "Howell",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Shanna@melissa.tv",
  },
  {
    id: 3,
    url: "https://picsum.photos/300",
    name: "Wrowell",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Nathan@yesenia.net",
  },
  {
    id: 4,
    url: "https://picsum.photos/301",
    name: "Patrici",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Julianne.OConner@kory.org",
  },
  {
    id: 5,
    url: "https://picsum.photos/302",
    name: "Chelsey",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Lucio_Hettinger@annie.ca",
  },
  {
    id: 6,
    url: "https://picsum.photos/303",
    name: "Schulist",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Karley_Dach@jasper.info",
  },
  {
    id: 7,
    url: "https://picsum.photos/304",
    name: "Weissnat",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Telly.Hoeger@billy.biz",
  },
  {
    id: 8,
    url: "https://picsum.photos/305",
    name: "Nicholas",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Sherwood@rosamond.me",
  },
  {
    id: 9,
    url: "https://picsum.photos/306",
    name: "Reichert",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Chaim_McDermott@dana.io",
  },
  {
    id: 10,
    url: "https://picsum.photos/307",
    name: "DuBuque",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Rey.Padberg@karina.biz",
  },
  {
    id: 11,
    url: "https://picsum.photos/308",
    name: "Clementina",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Rey.Padberg@karina.biz",
  },
  {
    id: 12,
    url: "https://picsum.photos/309",
    name: "Jementina",
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, nostrum illo.",
    email: "Rey.Padberg@karina.biz",
  },
];
